# movie_database.py

movie_database = {
    'hollywood': [
        {'name': 'Inception', 'theater': 'PVR Cinemas', 'timing': '12:00 PM'},
        {'name': 'The Dark Knight', 'theater': 'SPI Cinemas', 'timing': '2:30 PM'},
        {'name': 'Interstellar', 'theater': 'Palazzo Cinemas', 'timing': '5:00 PM'},
        {'name': 'Avengers: Endgame', 'theater': 'Escape Cinemas', 'timing': '7:30 PM'},
        {'name': 'La La Land', 'theater': 'INOX', 'timing': '10:00 PM'},
        {'name': 'Joker', 'theater': 'PVR Cinemas', 'timing': '1:00 PM'},
        {'name': 'Inception', 'theater': 'SPI Cinemas', 'timing': '3:30 PM'},
        {'name': 'Pulp Fiction', 'theater': 'Palazzo Cinemas', 'timing': '6:00 PM'},
        {'name': 'Titanic', 'theater': 'Escape Cinemas', 'timing': '8:30 PM'},
        {'name': 'The Godfather', 'theater': 'INOX', 'timing': '11:00 PM'},
        {'name': 'The Matrix', 'theater': 'INOX', 'timing': '12:00 PM'},
        {'name': 'The Shawshank Redemption', 'theater': 'SPI Cinemas', 'timing': '5:00 PM'},
        {'name': 'Jurassic Park', 'theater': 'Palazzo Cinemas', 'timing': '7:30 PM'},
        {'name': 'Forrest Gump', 'theater': 'Escape Cinemas', 'timing': '10:00 PM'},
        {'name': 'Avatar', 'theater': 'INOX', 'timing': '1:00 PM'},
        {'name': 'The Dark Knight Rises', 'theater': 'PVR Cinemas', 'timing': '3:30 PM'},
        {'name': 'Inglourious Basterds', 'theater': 'SPI Cinemas', 'timing': '6:00 PM'},
        {'name': 'The Great Gatsby', 'theater': 'Palazzo Cinemas', 'timing': '8:30 PM'},
        {'name': 'The Revenant', 'theater': 'Escape Cinemas', 'timing': '11:00 PM'},
    ],
    'bollywood': [
        {'name': 'Jawaan', 'theater': 'INOX', 'timing': '12:30 PM'},
        {'name': 'Pathan', 'theater': 'PVR Cinemas', 'timing': '3:00 PM'},
        {'name': 'Zindagi Na Milegi Dobara', 'theater': 'SPI Cinemas', 'timing': '5:30 PM'},
        {'name': 'Gully Boy', 'theater': 'Palazzo Cinemas', 'timing': '8:00 PM'},
        {'name': 'Andhadhun', 'theater': 'Escape Cinemas', 'timing': '10:30 PM'},
        {'name': 'Dil Chahta Hai', 'theater': 'INOX', 'timing': '1:30 PM'},
        {'name': 'Kahaani', 'theater': 'PVR Cinemas', 'timing': '4:00 PM'},
        {'name': 'PK', 'theater': 'SPI Cinemas', 'timing': '6:30 PM'},
        {'name': 'Dangal', 'theater': 'Palazzo Cinemas', 'timing': '9:00 PM'},
        {'name': 'Pad Man', 'theater': 'Escape Cinemas', 'timing': '11:30 PM'},
        {'name': 'Tiger Zinda Hai', 'theater': 'INOX', 'timing': '12:00 PM'},
        {'name': 'Chennai Express', 'theater': 'PVR Cinemas', 'timing': '2:30 PM'},
        {'name': 'Bajirao Mastani', 'theater': 'SPI Cinemas', 'timing': '5:00 PM'},
        {'name': 'Dilwale Dulhania Le Jayenge', 'theater': 'Palazzo Cinemas', 'timing': '7:30 PM'},
        {'name': 'Kabhi Khushi Kabhie Gham', 'theater': 'Escape Cinemas', 'timing': '10:00 PM'},
        {'name': 'Raees', 'theater': 'INOX', 'timing': '1:00 PM'},
        {'name': 'Padmaavat', 'theater': 'PVR Cinemas', 'timing': '3:30 PM'},
        {'name': 'Sultan', 'theater': 'SPI Cinemas', 'timing': '6:00 PM'},
        {'name': 'Bajrangi Bhaijaan', 'theater': 'Palazzo Cinemas', 'timing': '8:30 PM'},
        {'name': 'Secret Superstar', 'theater': 'Escape Cinemas', 'timing': '11:00 PM'},
        {'name': 'Dangal', 'theater': 'PVR Cinemas', 'timing': '12:30 PM'},
        {'name': 'PK', 'theater': 'INOX', 'timing': '3:00 PM'},
        {'name': '3 Idiots', 'theater': 'SPI Cinemas', 'timing': '5:30 PM'},
        {'name': 'Baahubali', 'theater': 'Palazzo Cinemas', 'timing': '8:00 PM'},
        {'name': 'Chennai Express', 'theater': 'Escape Cinemas', 'timing': '10:30 PM'},
        {'name': 'Dilwale', 'theater': 'INOX', 'timing': '1:30 PM'},
        {'name': 'Sultan', 'theater': 'PVR Cinemas', 'timing': '4:00 PM'},
        {'name': 'Padmaavat', 'theater': 'SPI Cinemas', 'timing': '6:30 PM'},
        {'name': 'Bajrangi Bhaijaan', 'theater': 'Palazzo Cinemas', 'timing': '9:00 PM'},
        {'name': 'Secret Superstar', 'theater': 'Escape Cinemas', 'timing': '11:30 PM'},
    ]
}
